Add filter method
mwilliamson/node-options pull request #10
Opened 2017-05-30 21:44 UTC by jbasrai

Scala's Option has a [filter](https://www.scala-lang.org/api/current/scala/Option.html#filter(p:A=>Boolean):Option[A]) method that is useful. I've found myself shimming this method for this library, so thought it might be worth including directly.

2017-05-30 22:28 UTC, mwilliamson requested changes
Thanks for the pull request, adding a `filter` method sounds sensible to me. I've left some comments on some of the code, let me know if anything doesn't make sense or you think I'm talking nonsense.

2017-05-30 22:28 UTC, mwilliamson commented on index.js
> +    });
This seems a little overcomplicated. Wouldn't the following accomplish the same thing?

```javascript
Some.prototype.filter = function(predicate) {
    return predicate(this._value) ? this : none;
};
```

2017-05-30 22:28 UTC, mwilliamson commented on test/options.test.js
> +exports.filteringSomeReturnsIdentityIfPredicateIsTrue = function(test) {
This test name doesn't seem quite right to me -- filtering when the predicate is true doesn't return the identity, it's equivalent to applying the identity. I think it'd be clearer to write the test name (including the other tests for filter) similarly to the docs e.g.

```javascript
exports["given predicate(value) is true then some(value).filter(predicate) is some(value)"] = ...
```

What do you think?

2017-05-30 22:28 UTC, mwilliamson commented on README.md
> +### filter(func)
Minor thing, but `func` should be surrounded by asterisks. Also, for `filter`, would calling the argument `predicate` be clearer than `func`?

2017-05-30 22:28 UTC, mwilliamson commented on index.js
> +Some.prototype.filter = function(f) {
Would calling the argument `predicate` be clearer than `f`?

2017-05-30 23:18 UTC, jbasrai reviewed
Thanks for the feedback. Completely agree with all the points you've made. I've made changes to reflect everything discussed.

2017-05-30 23:18 UTC, jbasrai commented on README.md
> +### filter(func)
Yup agree. I've changed all `func` arguments to be `predicate` instead.

2017-05-30 23:18 UTC, jbasrai commented on index.js
> +Some.prototype.filter = function(f) {
Yes!

2017-05-30 23:18 UTC, jbasrai commented on index.js
> +    });
Totally, this implementation is so much cleaner.

2017-05-30 23:18 UTC, jbasrai commented on test/options.test.js
> +exports.filteringSomeReturnsIdentityIfPredicateIsTrue = function(test) {
Agree! Think I'm using that word without knowing what it actually means. I've changed the names of the tests to be more practical similar to what you suggested.

2017-05-30 23:40 UTC, jbasrai commented
Sorry if I'm missing something in the review process. I noticed that the "Changes requested" label is still up. Let me know if I need to do something on my end besides pushing the changes!

2017-05-31 14:34 UTC, merged

2017-05-31 14:34 UTC, mwilliamson commented
Looks good, thanks!